trigger:
- master

pool:
  ubuntu
stages:
  - stage: Build
    jobs:
      - job:
        steps:
          - script: echo "testing"
        displayName: one line script

      - job:
        steps:
          - script: |
             echo "testing2
             sdfsdf
             sdfsdf"
        displayName: Multiline script