# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  ubuntu
stages:
  - stage: Build
    jobs:
      - job:
        steps:
          - script: echo "testing"
        displayName: one line script

