trigger:
- master

pool:
  ubuntu
stages:
  - stage: Build
    jobs:
      - job:
        steps:
          - script: echo "testing"
        displayName: one line script

      - job:
        steps:
          - script: |
             python --version
             node --version
        displayName: Multiline script